### ISSUE TITLE
Human-readable text in attributes

### ISSUE THREAD

**Issue by darobin** [bkardell/common-panel#6] opened 2015-01-09 16:00 UTC
I know it has been done elsewhere, but this is a problematic design because it interferes with I18N. You can have directionality markup or ruby for instance.

**Comment by bkardell** [comment] 2015-01-09 16:02
@darobin have a look at issue #1 and see if you can offer thoughts... resolving that might help answer this.

**Comment by bkardell** [comment] 2015-01-12 01:33
Duplicate of #1 since that was the only humanly readable attribute

**Closed as completed by bkardell** 2015-01-12 01:33 UTC
