### ISSUE TITLE
Use the HTML5 open attribute

### ISSUE THREAD

**Issue by LJWatson** [bkardell/common-panel#41] opened 2015-08-14 09:01 UTC
Would the existing open attribute serve instead of the proposed expandable attribute?
http://drafts.htmlwg.org/html/master/interactive-elements.html#attr-details-open

**Comment by bkardell** [comment] 2015-08-19 13:47
Duplicate of https://github.com/bkardell/common-panel/issues/33

**Closed as completed by bkardell** 2015-08-19 13:47 UTC
Labels: duplicate
